@startuml
'https://plantuml.com/class-diagram

class ReadwriteSplittingRuleConfiguration
class ReadwriteSplittingDataSourceRuleConfiguration
class ShardingSphereAlgorithmConfiguration

ReadwriteSplittingRuleConfiguration --> ReadwriteSplittingDataSourceRuleConfiguration
ReadwriteSplittingRuleConfiguration --> ShardingSphereAlgorithmConfiguration

@enduml